language: cpp
compiler: gcc
dist: xenial
sudo: required

notifications:
  email: false

before_install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt-5.11.1-xenial
  - sudo apt-get update -y

install:
  - sudo apt-get -y install wget curl qt511base qt511declarative qt511xmlpatterns
  - . /opt/qt511/bin/qt511-env.sh
  - wget https://cmake.org/files/v3.13/cmake-3.13.0-rc2-Linux-x86_64.sh -q
  - sudo sh cmake-3.13.0-rc2-Linux-x86_64.sh --prefix=/usr/local --exclude-subdir

script:
  - cmake .
  - make -j$(nproc)
  - make -j$(nproc) package
  - mv webdavclient-*.deb libwebdavclient.deb

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh libwebdavclient.deb

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
